name: flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.7.0
  flutter: ^3.29.0

dependencies:
  adaptive_dialog: ^2.4.0
  animated_text_kit: ^4.2.3
  animated_to: ^0.2.0
  auto_size_text: ^3.0.0
  collection: ^1.19.1
  cores_dependency_override:
    path: ../../packages/cores/dependency_override
  cores_designsystem:
    path: ../../packages/cores/designsystem
  cores_domain:
    path: ../../packages/cores/domain
  cupertino_icons: null
  device_preview: ^1.2.0
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_hooks: any
  flutter_localizations:
    sdk: flutter
  flutter_settings_ui: ^3.0.1
  flutter_svg: ^2.0.17
  freezed_annotation: any
  gap: any
  go_router: any
  hooks_riverpod: ^2.6.1
  intl: any
  json_annotation: any
  material_design_icons_flutter: ^7.0.7296
  mono_kit: ^0.41.0
  nested: null
  package_info_plus: ^8.2.1
  reactive_forms: ^17.0.1
  reactive_forms_annotations: ^6.0.0
  riverpod_annotation: ^2.6.1
  settings_ui: ^2.0.2
  slang: ^4.1.0
  slang_flutter: ^4.1.0
  version: null

dev_dependencies:
  build_runner: ^2.4.14
  build_verify: ^3.1.0
  custom_lint: ^0.7.0
  flutter_gen: ^5.8.0
  flutter_gen_runner: any
  flutter_test:
    sdk: flutter
  freezed: any
  go_router_builder: ^2.4.1
  icons_launcher: any
  json_serializable: any
  nilts: any
  pedantic_mono: any
  reactive_forms_generator: ^6.1.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true

  # Assets & Fonts
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/gen/assets
  assets:
    outputs:
      package_parameter_enabled: true

resolution: workspace
